# Car Insurance Claim Data Analysis

**Aviva** offers multiple products and services, spanning over pensions, insurnace and investments. One of their main insurnace products is Car insurance. Within this file, a car insurnace claim database will be uploaded and analysed to help shape Aviva's car insurance claim prediction model.


---



The code will be focused around this research question:
***"If a vehicle has poor saftey features, is the policyholder more likely to make a claim?"***


---



This notebook will:

1. Upload the relevant dataset
2. Profile the data
3. Clean the data- drop columns that are not needed and manage duplicates/null values
4. Create 3 visualisations to show comparisons of values
5. Create a machine learning model

# Setup

Before running the program the following install script will need to be ran. Skimpy is being used to help profile the data, which will be seen further down.

Once that is ran, the imports will then need to be ran. Each import has a difference purpose:


1.   pandas-
2.   numpy-
3.   google.colab-
4.   skimpy-

In [1]:
# Only run this once
!pip -q install skimpy -U

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.8/118.8 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 83.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.4/107.4 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 56.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires ipykernel==6.17.1, but you have ipykernel 7.2.0 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.1 which is incompatible.
jupyter-kernel-gateway 2.5.2 requires jupyter-client<8.0,>=5.2.0, but you have jupyter-client 8.8.0 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.1 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.1 which is incompatible.
notebook 6.5.7 requires jupyter-client<8,>=5.3.4, but you have jupyter-client 8.8.0 which is incompatible.
db-dtypes 1.5.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.1 which is incompatible.

In [2]:
# Run this everytime
import pandas as pd
import numpy as np
from google.colab import files
from skimpy import skim

## Upload Dataset

The database will need to be in a local file for the following upload to work.

Once the dataset is uploaded, a confirmation messaage is displayed to the user.

**Please note** without the below code running successfully, the other code blocks will not work.

In [4]:
# Please check that the database is in the correct file path
df = pd.read_csv("kaggleClaimData.csv")

print(f'Loaded database!')

Loaded database!

# Preprocessing

purpose

## Sample Data

Below sample data will be printed to visualise what the data currently looks like before data cleansing.

In [5]:
print("First five rows:")
df.head()

First five rows:

,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,is_claim
0,ID00001,0.515874,0.05,0.644231,C1,4990,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
1,ID00002,0.672619,0.02,0.375000,C2,27003,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
2,ID00003,0.841110,0.02,0.384615,C3,4076,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
3,ID00004,0.900277,0.11,0.432692,C4,21622,1,C1,M2,Petrol,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
4,ID00005,0.596403,0.11,0.634615,C5,34738,2,A,M3,Petrol,...,No,Yes,Yes,Yes,No,Yes,Yes,Yes,2,0

In [6]:
print("Last five rows:")
df.tail()

Last five rows:

,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,is_claim
58587,ID58588,0.355089,0.13,0.644231,C8,8794,2,A,M3,Petrol,...,No,Yes,Yes,Yes,No,Yes,Yes,Yes,2,0
58588,ID58589,1.199642,0.02,0.519231,C14,7788,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
58589,ID58590,1.162273,0.05,0.451923,C5,34738,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
58590,ID58591,1.236307,0.14,0.557692,C8,8794,1,B2,M6,Petrol,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
58591,ID58592,0.124429,0.02,0.442308,C8,8794,3,C2,M4,Diesel,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0

In [7]:
print('Random data sample')
df.sample(5)

Random data sample

,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,is_claim
6261,ID06262,0.254520,0.00,0.471154,C9,17804,3,C2,M4,Diesel,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
43438,ID43439,0.306567,0.01,0.490385,C15,290,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
37481,ID37482,0.640553,0.09,0.413462,C10,73430,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
55248,ID55249,0.806522,0.02,0.567308,C1,4990,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
1851,ID01852,0.094928,0.02,0.403846,C15,290,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0

In [10]:
print("Data dimensions: ", df.shape)

Data dimensions:  (58592, 44)

In [11]:
print("Dataset Information:")
df.info()

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 44 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         58592 non-null  str
 1   policy_tenure                     58592 non-null  float64
 2   age_of_car                        58592 non-null  float64
 3   age_of_policyholder               58592 non-null  float64
 4   area_cluster                      58592 non-null  str
 5   population_density                58592 non-null  int64
 6   make                              58592 non-null  int64
 7   segment                           58592 non-null  str
 8   model                             58592 non-null  str
 9   fuel_type                         58592 non-null  str
 10  max_torque                        58592 non-null  str
 11  max_power                         58592 non-null  str
 12  engine_type                       58592 non-null  str
 13  airbags                           58592 non-null  int64
 14  is_esc                            58592 non-null  str
 15  is_adjustable_steering            58592 non-null  str
 16  is_tpms                           58592 non-null  str
 17  is_parking_sensors                58592 non-null  str
 18  is_parking_camera                 58592 non-null  str
 19  rear_brakes_type                  58592 non-null  str
 20  displacement                      58592 non-null  int64
 21  cylinder                          58592 non-null  int64
 22  transmission_type                 58592 non-null  str
 23  gear_box                          58592 non-null  int64
 24  steering_type                     58592 non-null  str
 25  turning_radius                    58592 non-null  float64
 26  length                            58592 non-null  int64
 27  width                             58592 non-null  int64
 28  height                            58592 non-null  int64
 29  gross_weight                      58592 non-null  int64
 30  is_front_fog_lights               58592 non-null  str
 31  is_rear_window_wiper              58592 non-null  str
 32  is_rear_window_washer             58592 non-null  str
 33  is_rear_window_defogger           58592 non-null  str
 34  is_brake_assist                   58592 non-null  str
 35  is_power_door_locks               58592 non-null  str
 36  is_central_locking                58592 non-null  str
 37  is_power_steering                 58592 non-null  str
 38  is_driver_seat_height_adjustable  58592 non-null  str
 39  is_day_night_rear_view_mirror     58592 non-null  str
 40  is_ecw                            58592 non-null  str
 41  is_speed_alert                    58592 non-null  str
 42  ncap_rating                       58592 non-null  int64
 43  is_claim                          58592 non-null  int64
dtypes: float64(4), int64(12), str(28)
memory usage: 26.5 MB

## Data Profiling using skimpy

why using this?

In [15]:
skim(df)
# add error logging

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 58592  │ │ string      │ 28    │                                                          │
│ │ Number of columns │ 44     │ │ int64       │ 12    │                                                          │
│ └───────────────────┴────────┘ │ float64     │ 4     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━┳━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━━┓  │
│ ┃ column              ┃ NA ┃ NA % ┃ mean    ┃ sd      ┃ p0       ┃ p25    ┃ p50    ┃ p75    ┃ p100  ┃ hist   ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━╇━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━━┩  │
│ │    policy_tenure    │  0 │    0 │  0.6112 │  0.4142 │ 0.002735 │ 0.2102 │ 0.5738 │  1.039 │ 1.397 │ █▅▄▃▇▃ │  │
│ │     age_of_car      │  0 │    0 │ 0.06942 │ 0.05672 │        0 │   0.02 │   0.06 │   0.11 │     1 │   █    │  │
│ │ age_of_policyholder │  0 │    0 │  0.4694 │  0.1229 │   0.2885 │ 0.3654 │ 0.4519 │ 0.5481 │     1 │  █▇▄▂  │  │
│ │ population_density  │  0 │    0 │   18830 │   17660 │      290 │   6112 │   8794 │  27000 │ 73430 │ █▁▄  ▁ │  │
│ │        make         │  0 │    0 │   1.764 │   1.137 │        1 │      1 │      1 │      3 │     5 │  █  ▃  │  │
│ │       airbags       │  0 │    0 │   3.137 │   1.833 │        1 │      2 │      2 │      6 │     6 │  █   ▃ │  │
│ │    displacement     │  0 │    0 │    1162 │   266.3 │      796 │    796 │   1197 │   1493 │  1498 │ ▆▃ █ ▇ │  │
│ │      cylinder       │  0 │    0 │   3.627 │  0.4836 │        3 │      3 │      4 │      4 │     4 │ ▅    █ │  │
│ │      gear_box       │  0 │    0 │   5.245 │  0.4304 │        5 │      5 │      5 │      5 │     6 │ █    ▃ │  │
│ │   turning_radius    │  0 │    0 │   4.853 │  0.2281 │      4.5 │    4.6 │    4.8 │      5 │   5.2 │ █▂▇▃▂▇ │  │
│ │       length        │  0 │    0 │    3850 │   311.5 │     3445 │   3445 │   3845 │   3995 │  4300 │ ▇▃█▄ ▇ │  │
│ │        width        │  0 │    0 │    1672 │   112.1 │     1475 │   1515 │   1735 │   1755 │  1811 │ ▇▁▂▁█▇ │  │
│ │       height        │  0 │    0 │    1553 │   79.62 │     1475 │   1475 │   1530 │   1635 │  1825 │  █ ▃▁  │  │
│ │    gross_weight     │  0 │    0 │    1385 │   212.4 │     1051 │   1185 │   1335 │   1510 │  1720 │ ▂▆█▂▁▆ │  │
│ │     ncap_rating     │  0 │    0 │    1.76 │    1.39 │        0 │      0 │      2 │      3 │     5 │ ▇ █▅▁▁ │  │
│ │      is_claim       │  0 │    0 │ 0.06397 │  0.2447 │        0 │      0 │      0 │      0 │     1 │ █    ▁ │  │
│ └─────────────────────┴────┴──────┴─────────┴─────────┴──────────┴────────┴────────┴────────┴───────┴────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┓  │
│ ┃           ┃    ┃      ┃           ┃           ┃           ┃           ┃ chars per ┃ words per ┃ total      ┃  │
│ ┃ column    ┃ NA ┃ NA % ┃ shortest  ┃ longest   ┃ min       ┃ max       ┃ row       ┃ row       ┃ words      ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━┩  │
│ │ policy_id │  0 │    0 │  ID00001  │  ID00001  │  ID00001  │  ID58592  │         7 │         1 │      58592 │  │
│ │ area_clus │  0 │    0 │    C1     │    C10    │    C1     │    C9     │      2.28 │         1 │      58592 │  │
│ │    ter    │    │      │           │           │           │           │           │           │            │  │
│ │  segment  │  0 │    0 │     A     │  Utility  │     A     │  Utility  │      1.81 │         1 │      58592 │  │
│ │   model   │  0 │    0 │    M1     │    M10    │    M1     │    M9     │      2.03 │         1 │      58592 │  │
│ │ fuel_type │  0 │    0 │    CNG    │  Petrol   │    CNG    │  Petrol   │      4.96 │         1 │      58592 │  │
│ │ max_torqu │  0 │    0 │ 60Nm@3500 │ 82.1Nm@34 │ 113Nm@440 │ 91Nm@4250 │      12.8 │         1 │      58592 │  │
│ │     e     │    │      │    rpm    │   00rpm   │   0rpm    │    rpm    │           │           │            │  │
│ │ max_power │  0 │    0 │ 40.36bhp@ │ 113.45bhp │ 113.45bhp │ 97.89bhp@ │      16.2 │         1 │      58592 │  │
│ │           │    │      │  6000rpm  │ @4000rpm  │ @4000rpm  │  3600rpm  │           │           │            │  │
│ │ engine_ty │  0 │    0 │   K10C    │    1.5    │  1.0 SCe  │  i-DTEC   │      14.5 │       3.3 │     193165 │  │
│ │    pe     │    │      │           │ Turbochar │           │           │           │           │            │  │
│ │           │    │      │           │    ged    │           │           │           │           │            │  │
│ │           │    │      │           │ Revotorq  │           │           │           │           │            │  │
│ │  is_esc   │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.31 │         1 │      58592 │  │
│ │ is_adjust │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.61 │         1 │      58592 │  │
│ │ able_stee │    │      │           │           │           │           │           │           │            │  │
│ │   ring    │    │      │           │           │           │           │           │           │            │  │
│ │  is_tpms  │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.24 │         1 │      58592 │  │
│ │ is_parkin │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.96 │         1 │      58592 │  │
│ │ g_sensors │    │      │           │           │           │           │           │           │            │  │
│ │ is_parkin │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.39 │         1 │      58592 │  │
│ │ g_camera  │    │      │           │           │           │           │           │           │            │  │
│ │ rear_brak │  0 │    0 │   Drum    │   Drum    │   Disc    │   Drum    │         4 │         1 │      58592 │  │
│ │  es_type  │    │      │           │           │           │           │           │           │            │  │
│ │ transmiss │  0 │    0 │  Manual   │ Automatic │ Automatic │  Manual   │      7.05 │         1 │      58592 │  │
│ │ ion_type  │    │      │           │           │           │           │           │           │            │  │
│ │ steering_ │  0 │    0 │   Power   │ Electric  │ Electric  │   Power   │      6.24 │         1 │      58592 │  │
│ │   type    │    │      │           │           │           │           │           │           │            │  │
│ │ is_front_ │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.58 │         1 │      58592 │  │
│ │ fog_light │    │      │           │           │           │           │           │           │            │  │
│ │     s     │    │      │           │           │           │           │           │           │            │  │
│ │ is_rear_w │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.29 │         1 │      58592 │  │
│ │ indow_wip │    │      │           │           │           │           │           │           │            │  │
│ │    er     │    │      │           │           │           │           │           │           │            │  │
│ │ is_rear_w │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.29 │         1 │      58592 │  │
│ │ indow_was │    │      │           │           │           │           │           │           │            │  │
│ │    her    │    │      │           │           │           │           │           │           │            │  │
│ │ is_rear_w │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.35 │         1 │      58592 │  │
│ │ indow_def │    │      │           │           │           │           │           │           │            │  │
│ │   ogger   │    │      │           │           │           │           │           │           │            │  │
│ │ is_brake_ │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.55 │         1 │      58592 │  │
│ │  assist   │    │      │           │           │           │           │           │           │            │  │
│ │ is_power_ │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.72 │         1 │      58592 │  │
│ │ door_lock │    │      │           │           │           │           │           │           │            │  │
│ │     s     │    │      │           │           │           │           │           │           │            │  │
│ │ is_centra │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.72 │         1 │      58592 │  │
│ │ l_locking │    │      │           │           │           │           │           │           │            │  │
│ │ is_power_ │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.98 │         1 │      58592 │  │
│ │ steering  │    │      │           │           │           │           │           │           │            │  │
│ │ is_driver │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.59 │         1 │      58592 │  │
│ │ _seat_hei │    │      │           │           │           │           │           │           │            │  │
│ │ ght_adjus │    │      │           │           │           │           │           │           │            │  │
│ │   table   │    │      │           │           │           │           │           │           │            │  │
│ │ is_day_ni │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.38 │         1 │      58592 │  │
│ │ ght_rear_ │    │      │           │           │           │           │           │           │            │  │
│ │ view_mirr │    │      │           │           │           │           │           │           │            │  │
│ │    or     │    │      │           │           │           │           │           │           │            │  │
│ │  is_ecw   │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.72 │         1 │      58592 │  │
│ │ is_speed_ │  0 │    0 │    No     │    Yes    │    No     │    Yes    │      2.99 │         1 │      58592 │  │
│ │   alert   │    │      │           │           │           │           │           │           │            │  │
│ └───────────┴────┴──────┴───────────┴───────────┴───────────┴───────────┴───────────┴───────────┴────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

## Data cleansing

why?

Remove unnecssary columns first and why

In [ ]:
# code for removing columns

Talk about why I am checking null- will remove null values

In [ ]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

Now see and handle duplicates- remove

Then incorrect values- remove

Fix datatypes?

Handle outliers- use box plots

# EDA

## Visualisations

At least 3 vsiaulisations-

heatmap? box plot? one other?

# Refelection

* Discuss how the findings from the data can inform business intelligence.
* Reflect on the ethical considerations related to the data handling, analysis, and visualisation process.